export default {
	SET_BOOK_NAME: 'SET_BOOK_NAME',
	UPDATE_TOC: 'UPDATE_TOC',
	CHANGE_VIEW: 'CHANGE_VIEW',
	CLICK_SECTION_FROM_TOC: 'CLICK_SECTION_FROM_TOC',
	TO_NEXT_SECTION: 'TO_NEXT_SECTION',
	BACK_TO_TOC: 'BACK_TO_TOC',
	LOAD_SECTION_CONTENT: 'LOAD_SECTION_CONTENT',
	SET_ABSTAIN_TIME: 'SET_ABSTAIN_TIME',
};
